
services:
  postgres:
    image: postgres:13
    container_name: sales_postgres
    environment:
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: sales_pass
      POSTGRES_DB: sales
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mock-orders-api:
    build: ./scripts
    container_name: mock_orders_api
    ports:
      - "5000:5000"

  airflow-webserver:
    image: apache/airflow:2.7.2
    container_name: airflow_webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://sales_user:sales_pass@postgres/sales
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key_123
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
        --username admin
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com
        --password admin013 || true &&
      airflow webserver
      "


  airflow-scheduler:
    image: apache/airflow:2.7.2
    container_name: airflow_scheduler
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://sales_user:sales_pass@postgres/sales
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key_123
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt
    command: airflow scheduler

volumes:
  postgres-data:
